### ISSUE TITLE
Docker Compose questions

### ISSUE THREAD

**Issue by dlapin-cribl** [clhobbs/events-splitter#11]
1. How you would change your docker-compose file if you would need to have more targets (10, 100 etc.)
2. I see you've exposed ports for Targets and Splitter but not for Agent. Could you explain why?

**Comment by clhobbs** [comment]
1. Using this `docker-compose` I was able to create multiple targets:
```
version: '3.8'

services:

  Target:
    image: events-splitter
    environment:
      APP_MODE: 'target'
    expose:
      - 9997
    networks:
      - events-net
    scale: 10

  Splitter:
    image: events-splitter
    hostname: splitter
    container_name: Splitter
    environment:
      APP_MODE: 'splitter'
    expose:
      - 9997
    networks:
      - events-net
    depends_on:
      - Target

  Agent:
    image: events-splitter
    hostname: agent
    container_name: Agent
    environment:
      APP_MODE: 'agent'
    networks:
      - events-net
    depends_on:
      - Splitter

networks:
  events-net:
```
Before running `docker compose up -d` to spin up the containers, the image needs to be built using: `docker build -t events-splitter .`

I spent some time trying to figure out how I could get the `hostname` to include the "container number" (like `target_1, target_2, ... , target_10`) but I couldn't find a way to do that using `docker compose up`.  The best I could do was to set my `Target` service to this:
```
  Target:
    image: events-splitter
    hostname: 'target_$TARGET_NUM'
    environment:
      APP_MODE: 'target'
    expose:
      - 9997
    networks:
      - events-net

```
and then run `docker compose run` in a loop like this:
```
export TARGET_NUM=1
for i in {1..10}
do
    docker compose run -d -e "$${TARGET_NUM}=$i" Target
done
```

If you know of a way to achieve this using `docker compose up` I'd love to learn if it can be done.

2. I didn't expose port 9997 on the Agent because when I looked at the `agent()` and `splitter()` functions in app.js I didn't see any communication FROM the Splitter to the Agent.  My understanding of the `expose` option is that it's needed for the containers to communicate with each other via those exposed ports.  I guess ideally the Splitter could communicate back to the Agent with some acknowledgements and then I would need to expose the Agent port in that case.
